version: '3'
services:
  strapi:
    image: strapi/strapi
    container_name: yencons_strapi
    env_file: .env
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: 3307
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      NODE_ENV: production
      LETSENCRYPT_HOST: beta.duhocinterlink.com
      LETSENCRYPT_EMAIL: vudnd18@gmail.com
      VIRTUAL_HOST: beta.duhocinterlink.com
      VIRTUAL_PORT: 2000
    volumes:
      - ./:/srv/app
    ports:
      - "2000:1337"

networks:
  default:
    external:
      name: strapi_network